#!/usr/bin/env bash
set -euo pipefail

# -------------------------------
# Settings / paths
# -------------------------------
# This script lives in: <project-root>/Codebase/Setup
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Codebase dir: <project-root>/Codebase
CODEBASE_DIR="$(cd "$SCRIPT_DIR/../../" && pwd)"

# Project root: parent of Codebase
PROJECT_ROOT="$(cd "$CODEBASE_DIR/.." && pwd)"

# Directory holding all launch scripts we might bind (non-recursive):
#   <project-root>/Codebase
SCRIPTS_DIR="$CODEBASE_DIR"

# Put the xbindkeys config under project-root/UserData:
USERDATA_DIR="$PROJECT_ROOT/UserData"
XBINDSRC="$USERDATA_DIR/.xbindkeysrc"

# Ensure UserData exists
mkdir -p "$USERDATA_DIR"

# -------------------------------
# Always reset config on each run
# -------------------------------
cat > "$XBINDSRC" <<EOF
# xbindkeys configuration for DAGViewer
# Generated by Codebase/Setup/bind_hotkey.sh
# This file is overwritten each time bind_hotkey.sh is run.
EOF

# -------------------------------
# Sanity checks
# -------------------------------
if [[ ! -d "$SCRIPTS_DIR" ]]; then
    echo "Error: Codebase/ directory not found."
    echo "Expected here: $SCRIPTS_DIR"
    exit 1
fi

if ! command -v xbindkeys >/dev/null 2>&1; then
    echo "xbindkeys is not installed."
    read -rp "Install xbindkeys with 'sudo apt install xbindkeys'? [y/N] " ans
    ans="${ans:-n}"
    if [[ "$ans" =~ ^[Yy]$ ]]; then
        sudo apt update
        sudo apt install -y xbindkeys
    else
        echo "Cannot continue without xbindkeys."
        exit 1
    fi
fi

# -------------------------------
# Collect all candidate scripts in Codebase/ (non-recursive)
# -------------------------------
mapfile -d '' RUN_SCRIPTS < <(
    find "$SCRIPTS_DIR" -maxdepth 1 -type f -name '*.sh' \
        ! -name 'bind_hotkey.sh' \
        -print0 | sort -z
)

if (( ${#RUN_SCRIPTS[@]} == 0 )); then
    echo "No *.sh scripts found in $SCRIPTS_DIR to bind."
    exit 0
fi

cat <<EOF

================ HOTKEY BINDING SETUP ================
This will set up xbindkeys hotkeys for scripts directly under:

  $SCRIPTS_DIR

xbindkeys key format examples:
  "Control+Alt + t"
  "Mod4 + t"           (Super/Windows key + t)
  "Shift+Control + F12"

NOTE:
- Modifiers before '+' (Control, Shift, Alt, Mod4, etc.).
- Final token after '+' is the main key (t, F12, etc.).
- Leave the prompt **blank** to skip a script.

EOF

BOUND_ANY=false
declare -A USED_HOTKEYS=()

for SCRIPT_PATH in "${RUN_SCRIPTS[@]}"; do
    # Relative path just for nicer display
    REL_PATH="${SCRIPT_PATH#$PROJECT_ROOT/}"

    echo
    echo "--------------------------------------------------"
    echo "Script: $REL_PATH"

    # Ensure script is executable
    if [[ ! -x "$SCRIPT_PATH" ]]; then
        echo "Note: $REL_PATH is not executable."
        read -rp "  Make it executable with chmod +x? [Y/n] " ans
        ans="${ans:-y}"
        if [[ "$ans" =~ ^[Yy]$ ]]; then
            chmod +x "$SCRIPT_PATH"
            echo "  -> Made executable."
        else
            echo "  Skipping hotkey for non-executable script."
            continue
        fi
    fi

    # Ask if we should bind this script
    read -rp "Bind a hotkey to run this script? [y/N] " do_bind
    do_bind="${do_bind:-n}"
    if [[ ! "$do_bind" =~ ^[Yy]$ ]]; then
        echo "  Skipping $REL_PATH."
        continue
    fi

    # Ask for key combination
    while true; do
        read -rp "Enter key combination for '$REL_PATH' (blank to skip): " HOTKEY
        HOTKEY_TRIMMED="${HOTKEY// }"

        if [[ -z "$HOTKEY_TRIMMED" ]]; then
            echo "  No key entered. Skipping $REL_PATH."
            break
        fi

        if [[ -n "${USED_HOTKEYS[$HOTKEY_TRIMMED]:-}" ]]; then
            echo "  Warning: '$HOTKEY_TRIMMED' already used for:"
            echo "    ${USED_HOTKEYS[$HOTKEY_TRIMMED]}"
            read -rp "  Bind another script to the same hotkey anyway? [y/N] " dup
            dup="${dup:-n}"
            if [[ ! "$dup" =~ ^[Yy]$ ]]; then
                echo "  Choose a different hotkey."
                continue
            fi
        fi

        echo "  Binding '$HOTKEY' -> $REL_PATH"

        {
            echo
            echo "# Launch $REL_PATH"
            echo "\"$SCRIPT_PATH\""
            echo "  $HOTKEY"
        } >> "$XBINDSRC"

        USED_HOTKEYS[$HOTKEY_TRIMMED]="$REL_PATH"
        BOUND_ANY=true
        break
    done

done

if [[ "$BOUND_ANY" != true ]]; then
    echo
    echo "No hotkeys were configured. Nothing to restart."
    echo "Config file remains at: $XBINDSRC"
    exit 0
fi

# -------------------------------
# Restart xbindkeys with this config
# -------------------------------
echo
echo "Restarting xbindkeys with config: $XBINDSRC"

# Kill any existing xbindkeys
if pgrep -x xbindkeys >/dev/null 2>&1; then
    pkill xbindkeys || true
fi

# Start xbindkeys using this specific config file
xbindkeys -f "$XBINDSRC" &

echo
echo "Done!"
echo "Hotkeys are now bound for selected scripts in:"
echo "  $SCRIPTS_DIR"
echo
echo "Config is stored at:"
echo "  $XBINDSRC"
echo
echo "If hotkeys do not work, check:"
echo "  - You are using X11 (xbindkeys does not work on Wayland)."
echo "  - xbindkeys is running (this script just started it)."
echo "  - The key combos are valid in xbindkeys syntax."
